# Gaming and Mental Health Dataset Analysis

Exploratory Data Analysis (EDA) of a large dataset about gaming behavior and mental health.

Dataset source:
https://www.kaggle.com/datasets/sharmajicoder/gaming-and-mental-health

## 1. Import libraries

Import the neccessary Python libraries for data loading and analysis.

In [5]:
import kagglehub
import os
import pandas as pd

## 2. Descargar dataset

Download the latest version of the dataset directly from Kaggle.

In [15]:
path = kagglehub.dataset_download("sharmajicoder/gaming-and-mental-health")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'gaming-and-mental-health' dataset.
Path to dataset files: /kaggle/input/gaming-and-mental-health

## 3. Inspect Dataset Files

List the files included in the dataset directory to identify the CSV file.

In [16]:
os.listdir("/kaggle/input/gaming-and-mental-health")

['gaming_mental_health_10M_40features.csv']

## 4. Load Dataset

Load the dataset into a Pandas Dataframe for further analysis.

In [19]:
df = pd.read_csv("/kaggle/input/gaming-and-mental-health/gaming_mental_health_10M_40features.csv")
df.head()  # muestra las primeras filas

,age,gender,income,daily_gaming_hours,weekly_sessions,years_gaming,sleep_hours,caffeine_intake,exercise_hours,stress_level,...,parental_supervision,loneliness_score,aggression_score,happiness_score,bmi,screen_time_total,eye_strain_score,back_pain_score,competitive_rank,internet_quality
0,51,Female,8615,3.68,22,17,5.26,1.00,0.18,3,...,0,2.87,3.19,5.20,19.69,4.71,5.71,4.81,80,10
1,41,Female,39453,5.70,34,16,9.20,0.70,1.44,8,...,7,4.17,7.73,5.40,26.37,6.62,6.77,3.99,57,2
2,27,Male,40466,1.58,8,22,7.39,2.24,3.15,3,...,9,9.38,2.85,5.17,25.15,9.30,2.16,4.75,59,10
3,55,Male,51076,6.11,39,24,7.99,1.65,2.80,1,...,5,8.24,7.19,8.62,26.42,13.81,4.72,5.37,89,1
4,20,Male,86116,3.65,17,0,7.12,1.02,1.01,2,...,9,6.65,2.53,9.71,25.75,10.74,3.90,6.44,15,10

## 5. Initial Data Exploration

In this section we explore the structure of the dataset, including its size, columns, data types, and basic statistics. This helps us understand the data before performing deeper analysis.

### Dataset Size

Check the number of rows and columns in the dataset.

In [10]:
df.shape

(1000000, 39)

In [11]:
df.columns

Index(['age', 'gender', 'income', 'daily_gaming_hours', 'weekly_sessions',
       'years_gaming', 'sleep_hours', 'caffeine_intake', 'exercise_hours',
       'stress_level', 'anxiety_score', 'depression_score',
       'social_interaction_score', 'relationship_satisfaction',
       'academic_performance', 'work_productivity', 'addiction_level',
       'multiplayer_ratio', 'toxic_exposure', 'violent_games_ratio',
       'mobile_gaming_ratio', 'night_gaming_ratio', 'weekend_gaming_hours',
       'friends_gaming_count', 'online_friends', 'streaming_hours',
       'esports_interest', 'headset_usage', 'microtransactions_spending',
       'parental_supervision', 'loneliness_score', 'aggression_score',
       'happiness_score', 'bmi', 'screen_time_total', 'eye_strain_score',
       'back_pain_score', 'competitive_rank', 'internet_quality'],
      dtype='object')

### Dataset Structure

Inspect the data types and memory usage of the dataset.

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 39 columns):
 #   Column                      Non-Null Count    Dtype
---  ------                      --------------    -----
 0   age                         1000000 non-null  int64
 1   gender                      1000000 non-null  object
 2   income                      1000000 non-null  int64
 3   daily_gaming_hours          1000000 non-null  float64
 4   weekly_sessions             1000000 non-null  int64
 5   years_gaming                1000000 non-null  int64
 6   sleep_hours                 1000000 non-null  float64
 7   caffeine_intake             1000000 non-null  float64
 8   exercise_hours              1000000 non-null  float64
 9   stress_level                1000000 non-null  int64
 10  anxiety_score               1000000 non-null  float64
 11  depression_score            1000000 non-null  float64
 12  social_interaction_score    1000000 non-null  float64
 13  relationship_satisfaction   1000000 non-null  float64
 14  academic_performance        1000000 non-null  float64
 15  work_productivity           1000000 non-null  float64
 16  addiction_level             1000000 non-null  float64
 17  multiplayer_ratio           1000000 non-null  float64
 18  toxic_exposure              1000000 non-null  float64
 19  violent_games_ratio         1000000 non-null  float64
 20  mobile_gaming_ratio         1000000 non-null  float64
 21  night_gaming_ratio          1000000 non-null  float64
 22  weekend_gaming_hours        1000000 non-null  float64
 23  friends_gaming_count        1000000 non-null  int64
 24  online_friends              1000000 non-null  int64
 25  streaming_hours             1000000 non-null  float64
 26  esports_interest            1000000 non-null  int64
 27  headset_usage               1000000 non-null  int64
 28  microtransactions_spending  1000000 non-null  float64
 29  parental_supervision        1000000 non-null  int64
 30  loneliness_score            1000000 non-null  float64
 31  aggression_score            1000000 non-null  float64
 32  happiness_score             1000000 non-null  float64
 33  bmi                         1000000 non-null  float64
 34  screen_time_total           1000000 non-null  float64
 35  eye_strain_score            1000000 non-null  float64
 36  back_pain_score             1000000 non-null  float64
 37  competitive_rank            1000000 non-null  int64
 38  internet_quality            1000000 non-null  int64
dtypes: float64(26), int64(12), object(1)
memory usage: 297.5+ MB

### Basic Statistics

Generate summary statistics for numerical columns.

In [14]:
df.describe()

,age,income,daily_gaming_hours,weekly_sessions,years_gaming,sleep_hours,caffeine_intake,exercise_hours,stress_level,anxiety_score,...,parental_supervision,loneliness_score,aggression_score,happiness_score,bmi,screen_time_total,eye_strain_score,back_pain_score,competitive_rank,internet_quality
count,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.00000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,...,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000
mean,35.986005,77497.675955,3.999255,19.997540,12.002512,7.00053,1.997513,1.999008,5.497577,4.998644,...,4.996374,4.998520,5.000455,5.981822,24.003916,8.002032,4.998675,4.018777,49.448122,5.503339
std,13.557163,41851.540503,2.826307,11.253438,7.207838,1.50111,1.996174,1.999545,2.873248,1.977711,...,3.160810,1.977601,1.980307,1.956122,3.999927,3.998987,1.979308,1.956123,28.873153,2.871940
min,13.000000,5000.000000,0.000000,1.000000,0.000000,-0.17000,0.000000,0.000000,1.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,4.450000,0.070000,0.000000,0.000000,0.000000,1.000000
25%,24.000000,41258.000000,1.920000,10.000000,6.000000,5.99000,0.580000,0.580000,3.000000,3.650000,...,2.000000,3.650000,3.650000,4.650000,21.300000,5.070000,3.650000,2.660000,24.000000,3.000000
50%,36.000000,77521.000000,3.360000,20.000000,12.000000,7.00000,1.390000,1.390000,5.000000,5.000000,...,5.000000,5.000000,5.000000,6.000000,24.000000,7.350000,5.000000,4.000000,49.000000,6.000000
75%,48.000000,113697.000000,5.380000,30.000000,18.000000,8.01000,2.770000,2.770000,8.000000,6.350000,...,8.000000,6.350000,6.350000,7.350000,26.700000,10.220000,6.350000,5.350000,74.000000,8.000000
max,59.000000,149999.000000,30.420000,39.000000,24.000000,14.02000,26.900000,26.480000,10.000000,10.000000,...,10.000000,10.000000,10.000000,10.000000,43.600000,46.600000,10.000000,10.000000,99.000000,10.000000

### Random Sample of the Dataset

Display a few random rows to better understand the data.

In [20]:
df.sample(5) # filas aleatorias

,age,gender,income,daily_gaming_hours,weekly_sessions,years_gaming,sleep_hours,caffeine_intake,exercise_hours,stress_level,...,parental_supervision,loneliness_score,aggression_score,happiness_score,bmi,screen_time_total,eye_strain_score,back_pain_score,competitive_rank,internet_quality
647939,43,Female,64916,10.69,8,8,7.88,3.31,0.96,8,...,7,5.74,6.02,7.38,21.89,16.48,5.63,7.69,21,5
894935,24,Female,84150,2.48,24,10,7.13,8.86,4.22,7,...,0,6.47,3.55,3.54,20.50,11.80,6.02,4.32,81,6
595359,18,Female,59660,4.03,22,7,7.67,0.55,1.95,7,...,9,6.91,7.32,2.19,22.48,12.72,2.95,5.11,19,2
156310,44,Female,74193,4.19,2,3,7.81,0.36,0.22,8,...,4,5.91,5.55,3.55,21.44,7.76,7.53,4.17,75,8
587206,50,Male,66184,2.67,11,17,6.57,1.89,0.98,4,...,5,5.69,5.56,5.86,26.06,12.06,4.47,5.41,85,5

### Missing Values

Check for missing values in each column.

In [21]:
df.isnull().sum()

age                           0
gender                        0
income                        0
daily_gaming_hours            0
weekly_sessions               0
years_gaming                  0
sleep_hours                   0
caffeine_intake               0
exercise_hours                0
stress_level                  0
anxiety_score                 0
depression_score              0
social_interaction_score      0
relationship_satisfaction     0
academic_performance          0
work_productivity             0
addiction_level               0
multiplayer_ratio             0
toxic_exposure                0
violent_games_ratio           0
mobile_gaming_ratio           0
night_gaming_ratio            0
weekend_gaming_hours          0
friends_gaming_count          0
online_friends                0
streaming_hours               0
esports_interest              0
headset_usage                 0
microtransactions_spending    0
parental_supervision          0
loneliness_score              0
aggression_score              0
happiness_score               0
bmi                           0
screen_time_total             0
eye_strain_score              0
back_pain_score               0
competitive_rank              0
internet_quality              0
dtype: int64

### Create a Smaller Sample for Faster Exploration

Create a smaller subset of the dataset for quicker experimentation and analysis.

In [22]:
df_sample = df.sample(10000)

### Explore Key Variables

Inspect distributions of important variables such as gender and age.

In [26]:
df["gender"].value_counts()

gender
Male      480581
Female    479579
Other      39840
Name: count, dtype: int64

In [30]:
# df["age"].unique()
# sorted(df["age"].unique())
df["age"].value_counts().sort_index()

age
13    21291
14    21067
15    21355
16    21367
17    21569
18    21089
19    21170
20    21240
21    21134
22    21465
23    21173
24    21153
25    21297
26    21119
27    21560
28    21487
29    21327
30    21447
31    21190
32    21316
33    21332
34    21391
35    21401
36    21453
37    21418
38    21450
39    21160
40    21293
41    21435
42    21428
43    21031
44    21045
45    21053
46    21132
47    21143
48    21526
49    21354
50    21116
51    21163
52    21184
53    21457
54    21174
55    20926
56    21119
57    21320
58    21350
59    21330
Name: count, dtype: int64